### ISSUE TITLE
gmm model naming convention

### ISSUE THREAD

**Issue by wdanny69** [NavidKarami/Team-11-Capstone-Project#5]
is there any reason why the models are named *username*_15.wav.gmm instead of just *username*_gmm. it would be easier to read and identify this way

**Comment by NavidKarami** [comment]
15 indicates that 15 audio files were used for creating the model...so it gives good info. Also, .gmm is the file format so it would stay there. For me, it's easy to identify and know what belongs to who as it says Uzi_15.wav.gmm, Danny_15.wav.gmm....
